security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Nas\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            id: fos_user.user_provider.username

    firewalls:
        main_login:
            pattern : ^/login$
            anonymous: true
        main_Reset:
            pattern : ^/resetting
            anonymous: true			
        main:
            pattern: ^/
            anonymous: false
            provider: main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                always_use_default_target_path : true
                default_target_path: /
                use_referer : true				
            logout:
                path: fos_user_security_logout
                target: /				

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
