<?php

namespace Nas\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HonoraireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HonoraireRepository extends EntityRepository
{
	public function totalHonoraire($idSpe)
	{
		$qb = $this->_em->createQueryBuilder();
		
		$qb->select("SUM(h.pourcentageFacture)")
			->from('NasAppBundle:Honoraire', 'h')
			->where('h.specialite = :id')
			->setParameter('id', $idSpe);
		
		return $qb->getQuery()
					->getResult();		
	}

}
