<?php

namespace Nas\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InterventionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterventionRepository extends EntityRepository
{
	public function getSelectList($idSpecialite)
	{
		$qb = $this->createQueryBuilder('a')
					->where('a.specialite = '.$idSpecialite);
		
		return $qb;
	}
}
